[project]
<<<<<<< HEAD
name = "wsnetbuilder"
=======
name = "restgdf"
>>>>>>> 81afde2a84c137348ce9bed2a1b78d110ad4043c
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bmi-arcgis-restapi>=2.4.9",
<<<<<<< HEAD
    "folium>=0.18.0",
    "geopandas>=1.0.1",
    "ipykernel>=6.29.5",
    "keplergl>=0.3.7",
    "leafmap>=0.38.16",
    "networkx>=3.4.2",
    "owslib>=0.32.0",
    "requests>=2.32.3",
    "setuptools>=75.3.0",
    "streamlit>=1.40.0",
    "wntr>=1.3.2",
]
=======
    "cadquery>=2.5.2",
    "contextily>=1.6.2",
    "debugpy>=1.8.15",
    "ezdxf>=1.4.2",
    "folium>=0.20.0",
    "geopandas>=1.0.1",
    "ipykernel>=6.29.5",
    "ipython>=9.4.0",
    "leafmap>=0.48.6",
    "mapclassify>=2.10.0",
    "matplotlib>=3.10.3",
    "neovim>=0.3.1",
    "pyautocad>=0.2.0",
    "pydantic>=2.11.7",
    "pytest>=8.3.4",
    "pywr>=1.28.0",
    "setuptools>=80.9.0",
    "stormcatchments>=0.4.1",
    "whitebox>=2.3.6",
    "ydata-profiling>=4.12.2",
]

>>>>>>> 81afde2a84c137348ce9bed2a1b78d110ad4043c
